title: "Projeto-dev-web-grupo42"
baseurl: "" 
url: "https://nicldev.github.io/Projeto-dev-web-grupo42"

exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist
  - jekyll-github-metadata
